#pragma kernel CSMain
#pragma multi_compile_local WIWIW_WAVEFRONT_SIZE_16 WIWIW_WAVEFRONT_SIZE_32 WIWIW_WAVEFRONT_SIZE_64

// --------------------------------------------------------

#include "../../Utilities/Shaders/Library/LibCompute.hlsl"

// --------------------------------------------------------

RWTexture2D<float4> _Wiwiw_CubemapFaceTexture;

int _Wiwiw_CubemapFaceIndex;

// --------------------------------------------------------

WIWIW_NUMTHREADS
void CSMain(in uint3 id : SV_DispatchThreadID)
{

}

// --------------------------------------------------------
