#pragma kernel CSMain
#pragma multi_compile_local WIWIW_THREADS_PER_WAVE_16 WIWIW_THREADS_PER_WAVE_32 WIWIW_THREADS_PER_WAVE_64

// --------------------------------------------------------

#include "../../Utilities/Shaders/Library/GetGlobalBufferCoord3D.hlsl"
#include "../../Utilities/Shaders/Library/GetPerlinNoise.hlsl"
#include "../../Utilities/Shaders/Library/WaveFrontMultiCompile.hlsl"

// --------------------------------------------------------

RWTexture3D<float> _Wiwiw_DensityTexture;

// --------------------------------------------------------

WIWIW_NUMTHREADS
void CSMain(in uint3 id : SV_DispatchThreadID)
{
    const uint3 indexInCube = Wiwiw_GetGlobalBufferIndex3D(id.x);
    const float3 coordInCube = Wiwiw_GetGlobalBufferCoord3D(id.x);

    _Wiwiw_DensityTexture[indexInCube] = Wiwiw_GetPerlinNoise(coordInCube * 6.0);
}

// --------------------------------------------------------
